export const CONTENT_ITEM_MIN_WIDTH = 160;
export const CONTENT_ITEM_MIN_HEIGHT = 240;
export const CONTENT_ITEM_MAX_WIDTH = 200;
export const CONTENT_ITEM_MAX_HEIGHT = 300;
export const CONTENT_ITEM_GAP = 18;
export const MAX_ITEMS_PER_ROW = 6;
export const MIN_ITEMS_PER_ROW = 3;

export const CONTENT_LIST_MAX_WIDTH =
  (CONTENT_ITEM_MAX_WIDTH + CONTENT_ITEM_GAP) * MAX_ITEMS_PER_ROW;

export const CONTENT_LIST_MIN_WIDTH =
  (CONTENT_ITEM_MIN_WIDTH + CONTENT_ITEM_GAP) * MIN_ITEMS_PER_ROW;
